"""Build STATUS.md from every problem's meta.yaml.

Usage: python -m erdos.status [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from erdos._io import atomic_write_text
from erdos.meta import MetaError, ProblemMeta, load_meta

HEADER = "<!-- Generated by `python -m erdos.status`. Do not edit by hand. -->"


def collect(problems_root: Path) -> list[ProblemMeta]:
    metas: list[ProblemMeta] = []
    if problems_root.is_dir():
        for folder in sorted(problems_root.iterdir()):
            if folder.is_dir() and not folder.name.startswith(("_", ".")):
                metas.append(load_meta(folder))
    seen: dict[int, Path] = {}
    for meta in metas:
        if meta.number in seen:
            raise MetaError(
                f"problem {meta.number} appears in both {seen[meta.number].name} and {meta.folder.name}"
            )
        seen[meta.number] = meta.folder
    return sorted(metas, key=lambda m: m.number)


def render(metas: list[ProblemMeta]) -> str:
    lines = [HEADER, "", "# Status", ""]
    if not metas:
        lines.append("No problems attempted yet.")
    else:
        lines.append("| # | Problem | Site status | Our status | Verified | Observed | Conjectured |")
        lines.append("|---:|---|---|---|---:|---:|---:|")
        for m in metas:
            lines.append(
                f"| {m.number} | [{_escape(m.title)}](problems/{m.folder.name}/) | {m.site_status} "
                f"| {m.our_status} | {m.count('verified')} | {m.count('observed')} "
                f"| {m.count('conjectured')} |"
            )
    return "\n".join(lines) + "\n"


def _escape(text: str) -> str:
    for ch in ("\\", "|", "[", "]"):
        text = text.replace(ch, "\\" + ch)
    return text


def main(argv: list[str] | None = None, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build STATUS.md from problems/*/meta.yaml")
    parser.add_argument(
        "--check", action="store_true", help="fail if STATUS.md is out of date instead of writing it"
    )
    args = parser.parse_args(argv)
    root = root or Path.cwd()
    try:
        text = render(collect(root / "problems"))
    except MetaError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    target = root / "STATUS.md"
    if args.check:
        current = target.read_text(encoding="utf-8").replace("\r\n", "\n") if target.exists() else ""
        if current != text:
            print("error: STATUS.md is out of date; run `uv run python -m erdos.status`", file=sys.stderr)
            return 1
        return 0
    atomic_write_text(target, text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
